name: dart_mc_mod
description: Dart mod for Minecraft via native bridge
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.1.0
  nocterm:
    path: /Users/norbertkozsir/IdeaProjects/nocterm
  nocterm_minecraft:
    path: ../../nocterm_minecraft

dev_dependencies:
  ffigen: ^9.0.0
  lints: ^3.0.0
